sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip setuptools
  - pip install -e ".[testing]"
  - pip install pytest-cov
  - pip install python-coveralls

script:
 - py.test --cov tracim

after_success:
  - coveralls
